/* FILE: about-i18n.js */
window.ABOUT_I18N = {
  de: {
    pageTitle: "Lampadēphóros – Über uns",
    brandMini: "Der Fackelträger",
    h1: "Über uns",
    sub: "Lampadēphóros bedeutet „Fackelträger“: nicht laut, nicht grell – sondern Licht, das Orientierung gibt. Ein Weg aus Licht, Wasser, Herz und Stille.",
    note: "Kein Spam. Kein Drama. Nur Werk.",
    nav: {
      start: "Start",
      about: "Über uns",
      films: "Filme & Kapitel",
      impulses: "Impulse",
      workshop: "Werkstatt",
      offers: "Angebote",
      shop: "Shop",
      links: "Hier findest du uns"
    },
    cards: {
      c1h:"Wer ist Lampadēphóros?",
      c1p1:"Lampadēphóros ist ein kreatives Medienprojekt mit geistlicher Tiefe. Wir erzählen Geschichten, bauen Bilder, ordnen Gedanken – und suchen nach dem, was wirklich trägt.",
      c1p2:"Kurz: ein Ort für Menschen, die Licht wollen – ohne Lärm.",
      c2h:"Warum gibt es uns?",
      c2p:"Weil viele nach Sinn suchen – und oft nur Krach finden. Wir glauben: Stille ist nicht leer. Stille ist ein Raum. Und in diesem Raum kann Wahrheit wieder hörbar werden.",
      c3h:"Unser Ziel",
      c3p:"Sichtbarkeit ohne Lärm. Tiefe ohne Angst. Wir möchten Inhalte schaffen, die erden, aufrichten und das Herz wach machen – Schritt für Schritt.",
      c4h:"Wofür wir stehen",
      c4p1:"Klarheit statt Clickbait. Würde statt Drama. Schönheit statt Zynismus. Treue statt Trend.",
      c4p2:"Wir bauen langsam – aber echt.",
      c5h:"Was du hier findest",
      c5p:"Filme & Kapitel, Impulse, Werkstatt-Einblicke, Angebote (z. B. Pilgerreisen, Workshops, Vorträge) – und später auch einen Shop.",
      c5a:"Zur Übersicht →",
      c6h:"Mach den ersten Schritt",
      c6p:"Wenn du neu hier bist: Starte ruhig. Ein Film. Ein Impuls. Ein kleiner Schritt – aber bewusst.",
      c6a:"Zu Filme & Kapitel →"
    },
    footer: { lead: "© Lampadēphóros • Kontakt:" }
  },

  fr: {
    pageTitle: "Lampadēphóros – À propos",
    brandMini: "Le Porte-Flambeau",
    h1: "À propos",
    sub: "Lampadēphóros signifie « porteur de flambeau » : pas bruyant, pas clinquant – mais une lumière qui donne une direction. Un chemin de lumière, d’eau, de cœur et de silence.",
    note: "Pas de spam. Pas de drame. Juste l’œuvre.",
    nav:{ start:"Start", about:"À propos", films:"Films & chapitres", impulses:"Impulsions", workshop:"Atelier", offers:"Offres", shop:"Boutique", links:"Où nous trouver" },
    cards:{
      c1h:"Qui est Lampadēphóros ?",
      c1p1:"Lampadēphóros est un projet média créatif avec une profondeur spirituelle. Nous racontons, construisons des images, ordonnons des pensées – et cherchons ce qui porte vraiment.",
      c1p2:"En bref : un lieu pour ceux qui veulent de la lumière – sans bruit.",
      c2h:"Pourquoi existons-nous ?",
      c2p:"Parce que beaucoup cherchent du sens et ne trouvent que du vacarme. Nous croyons : le silence n’est pas vide. C’est un espace où la vérité peut redevenir audible.",
      c3h:"Notre objectif",
      c3p:"Visibilité sans bruit. Profondeur sans peur. Créer des contenus qui ancrent, relèvent et réveillent le cœur – pas à pas.",
      c4h:"Ce que nous défendons",
      c4p1:"Clarté plutôt que clickbait. Dignité plutôt que drame. Beauté plutôt que cynisme. Fidélité plutôt que tendance.",
      c4p2:"Nous construisons lentement – mais vrai.",
      c5h:"Ce que tu trouveras ici",
      c5p:"Films & chapitres, impulsions, coulisses de l’atelier, offres (pèlerinages, ateliers, conférences) – et plus tard une boutique.",
      c5a:"Vue d’ensemble →",
      c6h:"Fais le premier pas",
      c6p:"Si tu es nouveau : avance doucement. Un film. Une impulsion. Un petit pas – mais conscient.",
      c6a:"Vers Films & chapitres →"
    },
    footer:{ lead:"© Lampadēphóros • Contact :" }
  },

  en: {
    pageTitle: "Lampadēphóros – About",
    brandMini: "The Torchbearer",
    h1: "About",
    sub: "Lampadēphóros means “torchbearer”: not loud, not flashy—just light that helps you find your way. A path of light, water, heart, and silence.",
    note: "No spam. No drama. Just the work.",
    nav:{ start:"Start", about:"About", films:"Films & chapters", impulses:"Impulses", workshop:"Workshop", offers:"Offers", shop:"Shop", links:"Find us" },
    cards:{
      c1h:"Who is Lampadēphóros?",
      c1p1:"Lampadēphóros is a creative media project with spiritual depth. We tell stories, build images, order thoughts—and look for what truly holds.",
      c1p2:"In short: a place for people who want light—without noise.",
      c2h:"Why do we exist?",
      c2p:"Because many seek meaning and often find only noise. We believe: silence isn’t empty. It’s a space where truth can be heard again.",
      c3h:"Our aim",
      c3p:"Visibility without noise. Depth without fear. We want to create content that grounds, lifts, and wakes the heart—step by step.",
      c4h:"What we stand for",
      c4p1:"Clarity over clickbait. Dignity over drama. Beauty over cynicism. Faithfulness over trends.",
      c4p2:"We build slowly—but real.",
      c5h:"What you’ll find here",
      c5p:"Films & chapters, short impulses, workshop notes, offers (pilgrimages, workshops, talks)—and later a shop.",
      c5a:"Overview →",
      c6h:"Take the first step",
      c6p:"If you’re new: start gently. One film. One impulse. A small step—but intentional.",
      c6a:"Go to Films & chapters →"
    },
    footer:{ lead:"© Lampadēphóros • Contact:" }
  },

  pt: {
    pageTitle:"Lampadēphóros – Sobre",
    brandMini:"O Portador da Tocha",
    h1:"Sobre",
    sub:"Lampadēphóros significa “portador da tocha”: não é barulho, não é brilho falso — é luz que orienta. Um caminho de luz, água, coração e silêncio.",
    note:"Sem spam. Sem drama. Só obra.",
    nav:{ start:"Start", about:"Sobre", films:"Filmes & capítulos", impulses:"Impulsos", workshop:"Oficina", offers:"Ofertas", shop:"Loja", links:"Onde nos encontrar" },
    cards:{
      c1h:"Quem é Lampadēphóros?",
      c1p1:"Lampadēphóros é um projeto de mídia criativo com profundidade espiritual. Contamos histórias, criamos imagens, organizamos pensamentos — e buscamos o que realmente sustenta.",
      c1p2:"Em resumo: um lugar para quem quer luz — sem barulho.",
      c2h:"Por que existimos?",
      c2p:"Porque muitos procuram sentido e encontram apenas ruído. Cremos: o silêncio não é vazio. É um espaço onde a verdade pode voltar a ser ouvida.",
      c3h:"Nosso objetivo",
      c3p:"Visibilidade sem ruído. Profundidade sem medo. Criar conteúdos que enraízam, levantam e despertam o coração — passo a passo.",
      c4h:"O que defendemos",
      c4p1:"Clareza em vez de clickbait. Dignidade em vez de drama. Beleza em vez de cinismo. Fidelidade em vez de tendência.",
      c4p2:"Construímos devagar — mas de verdade.",
      c5h:"O que você encontra aqui",
      c5p:"Filmes & capítulos, impulsos, bastidores da oficina, ofertas (peregrinações, workshops, palestras) — e depois uma loja.",
      c5a:"Visão geral →",
      c6h:"Dê o primeiro passo",
      c6p:"Se você é novo: comece com calma. Um filme. Um impulso. Um pequeno passo — mas consciente.",
      c6a:"Ir para Filmes & capítulos →"
    },
    footer:{ lead:"© Lampadēphóros • Contato:" }
  },

  it: {
    pageTitle:"Lampadēphóros – Chi siamo",
    brandMini:"Il Portatore di Fiaccola",
    h1:"Chi siamo",
    sub:"Lampadēphóros significa “portatore di fiaccola”: non rumoroso, non abbagliante — ma luce che orienta. Un cammino di luce, acqua, cuore e silenzio.",
    note:"Niente spam. Niente drama. Solo opera.",
    nav:{ start:"Start", about:"Chi siamo", films:"Film & capitoli", impulses:"Spunti", workshop:"Laboratorio", offers:"Offerte", shop:"Shop", links:"Dove trovarci" },
    cards:{
      c1h:"Chi è Lampadēphóros?",
      c1p1:"Lampadēphóros è un progetto media creativo con profondità spirituale. Raccontiamo storie, costruiamo immagini, ordiniamo pensieri — e cerchiamo ciò che davvero sostiene.",
      c1p2:"In breve: un luogo per chi vuole luce — senza rumore.",
      c2h:"Perché esistiamo?",
      c2p:"Perché molti cercano senso e spesso trovano solo rumore. Crediamo: il silenzio non è vuoto. È uno spazio in cui la verità può tornare udibile.",
      c3h:"Il nostro obiettivo",
      c3p:"Visibilità senza rumore. Profondità senza paura. Creare contenuti che radicano, rialzano e risvegliano il cuore — passo dopo passo.",
      c4h:"Ciò in cui crediamo",
      c4p1:"Chiarezza invece di clickbait. Dignità invece di drama. Bellezza invece di cinismo. Fedeltà invece di trend.",
      c4p2:"Costruiamo lentamente — ma davvero.",
      c5h:"Cosa trovi qui",
      c5p:"Film & capitoli, spunti, dietro le quinte del laboratorio, offerte (pellegrinaggi, workshop, conferenze) — e poi uno shop.",
      c5a:"Panoramica →",
      c6h:"Fai il primo passo",
      c6p:"Se sei nuovo: inizia con calma. Un film. Uno spunto. Un piccolo passo — ma consapevole.",
      c6a:"Vai a Film & capitoli →"
    },
    footer:{ lead:"© Lampadēphóros • Contatto:" }
  },

  /* Für die übrigen Sprachen: Wir halten es bewusst kompakt, aber sauber. */
  es:{ pageTitle:"Lampadēphóros – Acerca de", brandMini:"El Portador de la Antorcha", h1:"Acerca de", sub:"Lampadēphóros significa “portador de la antorcha”: no ruidoso, no estridente—sino luz que orienta. Un camino de luz, agua, corazón y silencio.", note:"Sin spam. Sin drama. Solo obra.", nav:{start:"Start",about:"Acerca de",films:"Películas y capítulos",impulses:"Impulsos",workshop:"Taller",offers:"Ofertas",shop:"Tienda",links:"Dónde encontrarnos"}, cards:{c1h:"¿Quién es Lampadēphóros?",c1p1:"Un proyecto creativo con profundidad espiritual. Contamos historias, construimos imágenes, ordenamos ideas—y buscamos lo que sostiene de verdad.",c1p2:"En resumen: un lugar para quien quiere luz—sin ruido.",c2h:"¿Por qué existimos?",c2p:"Porque muchos buscan sentido y encuentran ruido. Creemos: el silencio no está vacío; es un espacio donde la verdad puede oírse de nuevo.",c3h:"Nuestro objetivo",c3p:"Visibilidad sin ruido. Profundidad sin miedo. Contenido que asienta, levanta y despierta el corazón—paso a paso.",c4h:"Lo que defendemos",c4p1:"Claridad antes que clickbait. Dignidad antes que drama. Belleza antes que cinismo. Fidelidad antes que tendencias.",c4p2:"Construimos despacio—pero real.",c5h:"Lo que encontrarás aquí",c5p:"Películas y capítulos, impulsos, taller, ofertas (peregrinaciones, talleres, charlas)—y más adelante una tienda.",c5a:"Ver →",c6h:"Da el primer paso",c6p:"Si eres nuevo: empieza tranquilo. Una película. Un impulso. Un pequeño paso—pero consciente.",c6a:"Ir a Películas y capítulos →"}, footer:{lead:"© Lampadēphóros • Contacto:"}},
  pl:{ pageTitle:"Lampadēphóros – O nas", brandMini:"Niosący Pochodnię", h1:"O nas", sub:"Lampadēphóros znaczy „niosący pochodnię”: nie głośno, nie krzykliwie—lecz światło, które prowadzi. Droga światła, wody, serca i ciszy.", note:"Bez spamu. Bez dramy. Tylko dzieło.", nav:{start:"Start",about:"O nas",films:"Filmy i rozdziały",impulses:"Impulsy",workshop:"Warsztat",offers:"Oferty",shop:"Sklep",links:"Gdzie nas znaleźć"}, cards:{c1h:"Kim jest Lampadēphóros?",c1p1:"Kreatywny projekt medialny z duchową głębią. Opowiadamy, budujemy obrazy, porządkujemy myśli—i szukamy tego, co naprawdę niesie.",c1p2:"Krótko: miejsce dla tych, którzy chcą światła—bez hałasu.",c2h:"Dlaczego istniejemy?",c2p:"Bo wielu szuka sensu i znajduje tylko zgiełk. Wierzymy: cisza nie jest pusta. To przestrzeń, gdzie prawdę znów słychać.",c3h:"Nasz cel",c3p:"Widoczność bez hałasu. Głębia bez lęku. Treści, które uziemiają, podnoszą i budzą serce—krok po kroku.",c4h:"Za czym stoimy",c4p1:"Jasność zamiast clickbaitu. Godność zamiast dramy. Piękno zamiast cynizmu. Wierność zamiast trendów.",c4p2:"Budujemy powoli—ale prawdziwie.",c5h:"Co tu znajdziesz",c5p:"Filmy i rozdziały, impulsy, warsztat, oferty (pielgrzymki, warsztaty, wykłady)—a później sklep.",c5a:"Przegląd →",c6h:"Zrób pierwszy krok",c6p:"Jeśli jesteś nowy: zacznij spokojnie. Film. Impuls. Mały krok—ale świadomy.",c6a:"Przejdź do Filmów i rozdziałów →"}, footer:{lead:"© Lampadēphóros • Kontakt:"}},
  ru:{ pageTitle:"Lampadēphóros – О нас", brandMini:"Факелоносец", h1:"О нас", sub:"Lampadēphóros означает «факелоносец»: не громко и не ярмарочно — а свет, который помогает найти путь. Путь света, воды, сердца и тишины.", note:"Без спама. Без драмы. Только дело.", nav:{start:"Start",about:"О нас",films:"Фильмы и главы",impulses:"Импульсы",workshop:"Мастерская",offers:"Предложения",shop:"Магазин",links:"Где мы есть"}, cards:{c1h:"Кто такой Lampadēphóros?",c1p1:"Творческий медиапроект с духовной глубиной. Мы рассказываем истории, строим образы, упорядочиваем мысли — и ищем то, что действительно держит.",c1p2:"Коротко: место для тех, кому нужен свет — без шума.",c2h:"Зачем мы существуем?",c2p:"Потому что многие ищут смысл и находят лишь шум. Мы верим: тишина не пуста. Это пространство, где истина снова слышна.",c3h:"Наша цель",c3p:"Видимость без шума. Глубина без страха. Контент, который заземляет, поднимает и пробуждает сердце — шаг за шагом.",c4h:"За что мы",c4p1:"Ясность вместо кликбейта. Достоинство вместо драмы. Красота вместо цинизма. Верность вместо трендов.",c4p2:"Мы строим медленно — но по-настоящему.",c5h:"Что ты найдёшь здесь",c5p:"Фильмы и главы, импульсы, мастерская, предложения (паломничества, мастер-классы, лекции) — и позже магазин.",c5a:"Обзор →",c6h:"Сделай первый шаг",c6p:"Если ты новичок: начни спокойно. Фильм. Импульс. Маленький шаг — но осознанный.",c6a:"К фильмам и главам →"}, footer:{lead:"© Lampadēphóros • Контакт:"}},

  nl:{ pageTitle:"Lampadēphóros – Over ons", brandMini:"De Fakkeldrager", h1:"Over ons", sub:"Lampadēphóros betekent ‘fakkeldrager’: niet luid, niet schreeuwerig—maar licht dat richting geeft. Een weg van licht, water, hart en stilte.", note:"Geen spam. Geen drama. Alleen werk.", nav:{start:"Start",about:"Over ons",films:"Films & hoofdstukken",impulses:"Impulsen",workshop:"Werkplaats",offers:"Aanbod",shop:"Shop",links:"Waar je ons vindt"}, cards:{c1h:"Wie is Lampadēphóros?",c1p1:"Een creatief mediaproject met spirituele diepte. We vertellen, bouwen beelden, ordenen gedachten—en zoeken wat echt draagt.",c1p2:"Kort: een plek voor mensen die licht willen—zonder lawaai.",c2h:"Waarom bestaan we?",c2p:"Omdat velen zin zoeken en vaak alleen ruis vinden. Wij geloven: stilte is niet leeg. Het is ruimte waar waarheid weer hoorbaar wordt.",c3h:"Ons doel",c3p:"Zichtbaarheid zonder lawaai. Diepte zonder angst. Content die grondt, optilt en het hart wakker maakt—stap voor stap.",c4h:"Waar we voor staan",c4p1:"Helderheid boven clickbait. Waardigheid boven drama. Schoonheid boven cynisme. Trouw boven trends.",c4p2:"We bouwen langzaam—maar echt.",c5h:"Wat je hier vindt",c5p:"Films & hoofdstukken, impulsen, werkplaats, aanbod (pelgrimages, workshops, lezingen)—en later een shop.",c5a:"Overzicht →",c6h:"Zet de eerste stap",c6p:"Nieuw hier? Begin rustig. Eén film. Eén impuls. Een kleine stap—maar bewust.",c6a:"Naar Films & hoofdstukken →"}, footer:{lead:"© Lampadēphóros • Contact:"}},
  ro:{ pageTitle:"Lampadēphóros – Despre", brandMini:"Purtătorul de Torță", h1:"Despre noi", sub:"Lampadēphóros înseamnă „purtător de torță”: nu zgomotos, nu strident—ci lumină care dă direcție. Un drum de lumină, apă, inimă și liniște.", note:"Fără spam. Fără dramă. Doar lucrarea.", nav:{start:"Start",about:"Despre",films:"Filme & capitole",impulses:"Impulsuri",workshop:"Atelier",offers:"Oferte",shop:"Magazin",links:"Unde ne găsești"}, cards:{c1h:"Cine este Lampadēphóros?",c1p1:"Un proiect media creativ cu profunzime spirituală. Spunem povești, construim imagini, ordonăm gânduri—și căutăm ceea ce susține cu adevărat.",c1p2:"Pe scurt: un loc pentru cei care vor lumină—fără zgomot.",c2h:"De ce existăm?",c2p:"Pentru că mulți caută sens și găsesc doar zgomot. Credem: liniștea nu e goală. E un spațiu unde adevărul poate fi auzit din nou.",c3h:"Scopul nostru",c3p:"Vizibilitate fără zgomot. Profunzime fără frică. Conținut care ancorează, ridică și trezește inima—pas cu pas.",c4h:"Pentru ce stăm",c4p1:"Claritate în loc de clickbait. Demnitate în loc de dramă. Frumusețe în loc de cinism. Fidelitate în loc de trend.",c4p2:"Construim încet—dar real.",c5h:"Ce găsești aici",c5p:"Filme & capitole, impulsuri, atelier, oferte (pelerinaje, workshopuri, conferințe)—și mai târziu un magazin.",c5a:"Privire de ansamblu →",c6h:"Fă primul pas",c6p:"Dacă ești nou: începe liniștit. Un film. Un impuls. Un pas mic—dar conștient.",c6a:"Către Filme & capitole →"}, footer:{lead:"© Lampadēphóros • Contact:"}},
  uk:{ pageTitle:"Lampadēphóros – Про нас", brandMini:"Факелоносець", h1:"Про нас", sub:"Lampadēphóros означає «факелоносець»: не гучно і не показово — а світло, що дає напрям. Шлях світла, води, серця й тиші.", note:"Без спаму. Без драми. Лише справа.", nav:{start:"Start",about:"Про нас",films:"Фільми та розділи",impulses:"Імпульси",workshop:"Майстерня",offers:"Пропозиції",shop:"Магазин",links:"Де нас знайти"}, cards:{c1h:"Хто такий Lampadēphóros?",c1p1:"Творчий медіапроєкт із духовною глибиною. Ми розповідаємо історії, будуємо образи, впорядковуємо думки — і шукаємо те, що справді тримає.",c1p2:"Коротко: місце для тих, хто хоче світла — без шуму.",c2h:"Навіщо ми існуємо?",c2p:"Бо багато хто шукає сенс і знаходить лише шум. Ми віримо: тиша не порожня. Це простір, де істина знову чутна.",c3h:"Наша мета",c3p:"Видимість без шуму. Глибина без страху. Контент, що заземлює, піднімає й пробуджує серце — крок за кроком.",c4h:"За що ми",c4p1:"Ясність замість клікбейту. Гідність замість драми. Краса замість цинізму. Вірність замість трендів.",c4p2:"Ми будуємо повільно — але по-справжньому.",c5h:"Що ти знайдеш тут",c5p:"Фільми та розділи, імпульси, майстерня, пропозиції (паломництва, воркшопи, лекції) — і згодом магазин.",c5a:"Огляд →",c6h:"Зроби перший крок",c6p:"Якщо ти новий: почни спокійно. Один фільм. Один імпульс. Маленький крок — але свідомий.",c6a:"До Фільмів та розділів →"}, footer:{lead:"© Lampadēphóros • Контакт:"}},

  hr:{ pageTitle:"Lampadēphóros – O nama", brandMini:"Nositelj Baklje", h1:"O nama", sub:"Lampadēphóros znači „nositelj baklje“: ne glasno, ne blještavo — nego svjetlo koje daje smjer. Put svjetla, vode, srca i tišine.", note:"Bez spama. Bez drame. Samo djelo.", nav:{start:"Start",about:"O nama",films:"Filmovi i poglavlja",impulses:"Impulsi",workshop:"Radionica",offers:"Ponude",shop:"Trgovina",links:"Gdje nas naći"}, cards:{c1h:"Tko je Lampadēphóros?",c1p1:"Kreativan medijski projekt s duhovnom dubinom. Pričamo priče, gradimo slike, uređujemo misli — i tražimo ono što stvarno nosi.",c1p2:"Ukratko: mjesto za one koji žele svjetlo — bez buke.",c2h:"Zašto postojimo?",c2p:"Jer mnogi traže smisao i često nalaze samo buku. Vjerujemo: tišina nije prazna. To je prostor gdje istina opet postaje čujna.",c3h:"Naš cilj",c3p:"Vidljivost bez buke. Dubina bez straha. Sadržaj koji uzemljuje, podiže i budi srce — korak po korak.",c4h:"Za što stojimo",c4p1:"Jasnoća umjesto clickbaita. Dostojanstvo umjesto drame. Ljepota umjesto cinizma. Vjernost umjesto trendova.",c4p2:"Gradimo polako — ali stvarno.",c5h:"Što ovdje nalaziš",c5p:"Filmove i poglavlja, impulse, radionicu, ponude (hodočašća, radionice, predavanja) — i kasnije trgovinu.",c5a:"Pregled →",c6h:"Napravi prvi korak",c6p:"Ako si nov: kreni mirno. Jedan film. Jedan impuls. Mali korak — ali svjestan.",c6a:"Na Filmove i poglavlja →"}, footer:{lead:"© Lampadēphóros • Kontakt:"}},
  bs:{ pageTitle:"Lampadēphóros – O nama", brandMini:"Nosioc Baklje", h1:"O nama", sub:"Lampadēphóros znači „nosioc baklje“: ne glasno, ne blještavo — nego svjetlo koje daje smjer. Put svjetla, vode, srca i tišine.", note:"Bez spama. Bez drame. Samo djelo.", nav:{start:"Start",about:"O nama",films:"Filmovi i poglavlja",impulses:"Impulsi",workshop:"Radionica",offers:"Ponude",shop:"Shop",links:"Gdje nas naći"}, cards:{c1h:"Ko je Lampadēphóros?",c1p1:"Kreativan medijski projekt s duhovnom dubinom. Pričamo priče, gradimo slike, uređujemo misli — i tražimo ono što zaista nosi.",c1p2:"Ukratko: mjesto za one koji žele svjetlo — bez buke.",c2h:"Zašto postojimo?",c2p:"Jer mnogi traže smisao i često nalaze samo buku. Vjerujemo: tišina nije prazna. To je prostor gdje istina opet postaje čujna.",c3h:"Naš cilj",c3p:"Vidljivost bez buke. Dubina bez straha. Sadržaj koji uzemljuje, podiže i budi srce — korak po korak.",c4h:"Za šta stojimo",c4p1:"Jasnoća umjesto clickbaita. Dostojanstvo umjesto drame. Ljepota umjesto cinizma. Vjernost umjesto trendova.",c4p2:"Gradimo polako — ali stvarno.",c5h:"Šta ovdje nađeš",c5p:"Filmove i poglavlja, impulse, radionicu, ponude (hodočašća, radionice, predavanja) — i kasnije shop.",c5a:"Pregled →",c6h:"Napravi prvi korak",c6p:"Ako si nov: kreni mirno. Jedan film. Jedan impuls. Mali korak — ali svjestan.",c6a:"Na Filmove i poglavlja →"}, footer:{lead:"© Lampadēphóros • Kontakt:"}},
  sr:{ pageTitle:"Lampadēphóros – О нама", brandMini:"Носилац Бакље", h1:"О нама", sub:"Lampadēphóros значи „носилац бакље“: не гласно, не бљештаво — већ светло које даје смер. Пут светла, воде, срца и тишине.", note:"Без спама. Без драме. Само дело.", nav:{start:"Start",about:"О нама",films:"Филмови и поглавља",impulses:"Импулси",workshop:"Радионица",offers:"Понуде",shop:"Продавница",links:"Где нас наћи"}, cards:{c1h:"Ко је Lampadēphóros?",c1p1:"Креативан медијски пројекат са духовном дубином. Причамо приче, градимо слике, уређујемо мисли — и тражимо оно што заиста носи.",c1p2:"Укратко: место за оне који желе светло — без буке.",c2h:"Зашто постојимо?",c2p:"Јер многи траже смисао и често налазе само буку. Верујемо: тишина није празна. То је простор где истина поново постаје чујна.",c3h:"Наш циљ",c3p:"Видљивост без буке. Дубина без страха. Садржај који приземљује, подиже и буди срце — корак по корак.",c4h:"За шта стојимо",c4p1:"Јасноћа уместо кликбејта. Достојанство уместо драме. Лепота уместо цинизма. Верност уместо трендова.",c4p2:"Градимо споро — али стварно.",c5h:"Шта овде налазиш",c5p:"Филмове и поглавља, импулсе, радионицу, понуде (ходочашћа, радионице, предавања) — и касније продавницу.",c5a:"Преглед →",c6h:"Направи први корак",c6p:"Ако си нов: крени мирно. Један филм. Један импулс. Мали корак — али свестан.",c6a:"На Филмове и поглавља →"}, footer:{lead:"© Lampadēphóros • Контакт:"}},

  ar:{ pageTitle:"Lampadēphóros – من نحن", brandMini:"حامل المشعل", h1:"من نحن", sub:"Lampadēphóros تعني «حامل المشعل»: ليس صخبًا ولا استعراضًا، بل نورًا يهدي الطريق. مسار من نور وماء وقلب وصمت.", note:"لا سبام. لا دراما. فقط العمل.", nav:{start:"Start",about:"من نحن",films:"أفلام وفصول",impulses:"ومضات",workshop:"ورشة",offers:"عروض",shop:"متجر",links:"أين تجدنا"}, cards:{c1h:"من هو Lampadēphóros؟",c1p1:"مشروع إعلامي إبداعي بعمق روحي. نروي قصصًا، نبني صورًا، نرتب أفكارًا—ونبحث عمّا يثبت حقًا.",c1p2:"باختصار: مكان لمن يريد النور—بلا ضجيج.",c2h:"لماذا وُجدنا؟",c2p:"لأن كثيرين يبحثون عن معنى ويجدون ضوضاء. نؤمن: الصمت ليس فراغًا، بل مساحة تُسمَع فيها الحقيقة من جديد.",c3h:"هدفنا",c3p:"ظهور بلا ضجيج. عمق بلا خوف. محتوى يرسّخ ويرفع ويوقظ القلب—خطوة بخطوة.",c4h:"ماذا نمثل؟",c4p1:"وضوح بدل الطُعم. كرامة بدل الدراما. جمال بدل السخرية. أمانة بدل الموضات.",c4p2:"نبني ببطء—لكن بصدق.",c5h:"ماذا ستجد هنا؟",c5p:"أفلام وفصول، ومضات، ورشة، عروض (حجّ، ورش، محاضرات)—ولا حقًا متجر.",c5a:"نظرة عامة →",c6h:"ابدأ الخطوة الأولى",c6p:"إن كنت جديدًا: ابدأ بهدوء. فيلم واحد. ومضة واحدة. خطوة صغيرة—لكن بوعي.",c6a:"إلى الأفلام والفصول →"}, footer:{lead:"© Lampadēphóros • تواصل:"}},
  ur:{ pageTitle:"Lampadēphóros – ہمارے بارے میں", brandMini:"مشعل بردار", h1:"ہمارے بارے میں", sub:"Lampadēphóros کا مطلب ہے “مشعل بردار”: نہ شور، نہ دکھاوا—بس وہ روشنی جو راستہ دکھائے۔ روشنی، پانی، دل اور خاموشی کا سفر۔", note:"نہ اسپام۔ نہ ڈرامہ۔ بس کام۔", nav:{start:"Start",about:"ہمارے بارے میں",films:"فلمیں اور ابواب",impulses:"اشارے",workshop:"ورکشاپ",offers:"پیشکشیں",shop:"دکان",links:"ہمیں کہاں پائیں"}, cards:{c1h:"Lampadēphóros کون ہے؟",c1p1:"روحانی گہرائی کے ساتھ ایک تخلیقی میڈیا پروجیکٹ۔ ہم کہانیاں سناتے ہیں، تصاویر بناتے ہیں، خیالات ترتیب دیتے ہیں—اور اس چیز کو ڈھونڈتے ہیں جو واقعی سنبھالے۔",c1p2:"مختصر: اُن لوگوں کے لیے جگہ جو روشنی چاہتے ہیں—بغیر شور۔",c2h:"ہم کیوں موجود ہیں؟",c2p:"کیونکہ بہت سے لوگ معنی ڈھونڈتے ہیں اور صرف شور پاتے ہیں۔ ہم مانتے ہیں: خاموشی خالی نہیں۔ یہ وہ جگہ ہے جہاں سچ پھر سنائی دیتا ہے۔",c3h:"ہمارا مقصد",c3p:"شور کے بغیر نمایاں ہونا۔ خوف کے بغیر گہرائی۔ ایسا مواد جو جڑ دے، اٹھائے اور دل کو جگائے—قدم بہ قدم۔",c4h:"ہم کس کے لیے کھڑے ہیں",c4p1:"کلک بیٹ کے بجائے وضاحت۔ ڈرامے کے بجائے وقار۔ طنز کے بجائے خوبصورتی۔ رجحان کے بجائے وفاداری۔",c4p2:"ہم آہستہ بناتے ہیں—مگر حقیقی۔",c5h:"یہاں کیا ملے گا",c5p:"فلمیں اور ابواب، اشارے، ورکشاپ، پیشکشیں (زیارتیں، ورکشاپس، لیکچرز)—اور بعد میں ایک دکان۔",c5a:"جائزہ →",c6h:"پہلا قدم اٹھائیں",c6p:"اگر آپ نئے ہیں: آہستہ شروع کریں۔ ایک فلم۔ ایک اشارہ۔ ایک چھوٹا قدم—مگر شعوری۔",c6a:"فلمیں اور ابواب →"}, footer:{lead:"© Lampadēphóros • رابطہ:"}},
  fa:{ pageTitle:"Lampadēphóros – درباره ما", brandMini:"مشعل‌دار", h1:"درباره ما", sub:"Lampadēphóros یعنی «مشعل‌دار»: نه پر سر و صدا، نه نمایشی—بلکه نوری که راه را نشان می‌دهد. راهی از نور، آب، دل و سکوت.", note:"بدون اسپم. بدون دراما. فقط کار.", nav:{start:"Start",about:"درباره ما",films:"فیلم‌ها و فصل‌ها",impulses:"الهام‌ها",workshop:"کارگاه",offers:"پیشنهادها",shop:"فروشگاه",links:"کجا پیدایمان کنید"}, cards:{c1h:"Lampadēphóros کیست؟",c1p1:"یک پروژه رسانه‌ای خلاق با عمق روحانی. داستان می‌گوییم، تصویر می‌سازیم، فکرها را مرتب می‌کنیم—و دنبال چیزی هستیم که واقعاً نگه می‌دارد.",c1p2:"خلاصه: جایی برای کسانی که نور می‌خواهند—بی‌سر و صدا.",c2h:"چرا هستیم؟",c2p:"چون بسیاری دنبال معنا هستند و فقط سروصدا می‌یابند. باور داریم: سکوت خالی نیست؛ فضایی است که حقیقت دوباره شنیده می‌شود.",c3h:"هدف ما",c3p:"دیده‌شدن بدون سروصدا. عمق بدون ترس. محتوایی که ریشه می‌دهد، بلند می‌کند و قلب را بیدار می‌کند—قدم‌به‌قدم.",c4h:"ارزش‌های ما",c4p1:"شفافیت به‌جای کلیک‌بیت. وقار به‌جای دراما. زیبایی به‌جای بدبینی. وفاداری به‌جای مُد.",c4p2:"آهسته می‌سازیم—اما واقعی.",c5h:"اینجا چه می‌یابی؟",c5p:"فیلم‌ها و فصل‌ها، الهام‌ها، کارگاه، پیشنهادها (زیارت‌ها، کارگاه‌ها، سخنرانی‌ها)—و بعداً فروشگاه.",c5a:"نمای کلی →",c6h:"قدم اول را بردار",c6p:"اگر تازه‌ای: آرام شروع کن. یک فیلم. یک الهام. یک قدم کوچک—اما آگاهانه.",c6a:"به فیلم‌ها و فصل‌ها →"}, footer:{lead:"© Lampadēphóros • تماس:"}},
  tr:{ pageTitle:"Lampadēphóros – Hakkımızda", brandMini:"Meşale Taşıyıcısı", h1:"Hakkımızda", sub:"Lampadēphóros “meşale taşıyıcısı” demektir: gürültü değil, gösteriş değil—yolu aydınlatan bir ışık. Işık, su, kalp ve sessizliğin yolu.", note:"Spam yok. Drama yok. Sadece iş.", nav:{start:"Start",about:"Hakkımızda",films:"Filmler ve bölümler",impulses:"Esinler",workshop:"Atölye",offers:"Teklifler",shop:"Mağaza",links:"Bizi bulun"}, cards:{c1h:"Lampadēphóros kim?",c1p1:"Ruhsal derinliği olan yaratıcı bir medya projesi. Hikâyeler anlatır, görüntüler kurar, düşünceleri düzenler—ve gerçekten taşıyanı ararız.",c1p2:"Kısaca: ışık isteyenler için—gürültüsüz bir yer.",c2h:"Neden varız?",c2p:"Çünkü birçok kişi anlam arıyor ve sadece gürültü buluyor. İnanıyoruz: sessizlik boş değildir. Gerçeğin yeniden duyulduğu bir alandır.",c3h:"Hedefimiz",c3p:"Gürültüsüz görünürlük. Korkusuz derinlik. Topraklayan, kaldıran ve kalbi uyandıran içerikler—adım adım.",c4h:"Neyi savunuyoruz",c4p1:"Clickbait yerine açıklık. Drama yerine onur. Alaycılık yerine güzellik. Trend yerine sadakat.",c4p2:"Yavaş inşa ederiz—ama gerçek.",c5h:"Burada ne var?",c5p:"Filmler ve bölümler, esinler, atölye, teklifler (hac/pilgrimage, atölyeler, konuşmalar)—ve sonra mağaza.",c5a:"Genel bakış →",c6h:"İlk adımı at",c6p:"Yeniysen: sakin başla. Bir film. Bir esin. Küçük bir adım—ama bilinçli.",c6a:"Filmler ve bölümlere →"}, footer:{lead:"© Lampadēphóros • İletişim:"}},

  zh:{ pageTitle:"Lampadēphóros – 关于我们", brandMini:"火炬携带者", h1:"关于我们", sub:"Lampadēphóros 意为“火炬携带者”：不喧哗、不炫目，而是指引方向的光。光、水、心与静的道路。", note:"无垃圾信息。无戏剧。只有作品。", nav:{start:"Start",about:"关于",films:"影片与章节",impulses:"短引",workshop:"工坊",offers:"活动",shop:"商店",links:"在哪里找到我们"}, cards:{c1h:"Lampadēphóros 是谁？",c1p1:"一个具有灵性深度的创意媒体项目。我们讲故事、构建影像、整理思想——寻找真正能承载的东西。",c1p2:"简而言之：给想要光的人——不需要噪音。",c2h:"我们为何存在？",c2p:"因为很多人寻找意义，却只遇到喧嚣。我们相信：静默不是空的，它是让真理再次可听见的空间。",c3h:"我们的目标",c3p:"无噪音的可见度。无恐惧的深度。做能扎根、扶起并唤醒内心的内容——一步一步。",c4h:"我们的立场",c4p1:"清晰胜过标题党。尊严胜过闹剧。美胜过冷嘲。忠诚胜过潮流。",c4p2:"我们慢慢建造——但真实。",c5h:"你会在这里找到",c5p:"影片与章节、短引、工坊记录、活动（朝圣、工作坊、讲座）——以后还有商店。",c5a:"总览 →",c6h:"迈出第一步",c6p:"如果你是新来的：慢慢开始。一部影片。一段短引。小小一步——但有意识。",c6a:"前往影片与章节 →"}, footer:{lead:"© Lampadēphóros • 联系:"}},
  hi:{ pageTitle:"Lampadēphóros – हमारे बारे में", brandMini:"मशालवाहक", h1:"हमारे बारे में", sub:"Lampadēphóros का अर्थ है “मशालवाहक”: न शोर, न दिखावा—बस वह प्रकाश जो दिशा देता है। प्रकाश, पानी, हृदय और मौन का मार्ग।", note:"कोई स्पैम नहीं। कोई ड्रामा नहीं। सिर्फ कार्य।", nav:{start:"Start",about:"हमारे बारे में",films:"फिल्में व अध्याय",impulses:"संकेत",workshop:"वर्कशॉप",offers:"प्रस्ताव",shop:"दुकान",links:"हमें कहाँ पाएँ"}, cards:{c1h:"Lampadēphóros कौन है?",c1p1:"आध्यात्मिक गहराई वाला एक रचनात्मक मीडिया प्रोजेक्ट। हम कहानियाँ कहते हैं, चित्र बनाते हैं, विचारों को क्रम देते हैं—और जो सच में सहारा देता है उसे खोजते हैं।",c1p2:"संक्षेप में: उन लोगों के लिए जगह जो प्रकाश चाहते हैं—बिना शोर।",c2h:"हम क्यों हैं?",c2p:"क्योंकि बहुत लोग अर्थ खोजते हैं और केवल शोर पाते हैं। हम मानते हैं: मौन खाली नहीं। यह वह स्थान है जहाँ सत्य फिर सुनाई देता है।",c3h:"हमारा लक्ष्य",c3p:"शोर के बिना दृश्यता। भय के बिना गहराई। ऐसा कंटेंट जो जड़ देता है, उठाता है और हृदय जगाता है—कदम दर कदम।",c4h:"हम किसके लिए खड़े हैं",c4p1:"क्लिकबेट नहीं, स्पष्टता। ड्रामा नहीं, गरिमा। निंदकता नहीं, सुंदरता। ट्रेंड नहीं, निष्ठा।",c4p2:"हम धीरे बनाते हैं—पर सच्चे।",c5h:"यहाँ क्या मिलेगा",c5p:"फिल्में व अध्याय, संकेत, वर्कशॉप/वर्कशॉप-नोट्स, प्रस्ताव (तीर्थयात्रा, कार्यशाला, वक्तव्य)—और बाद में दुकान।",c5a:"सारांश →",c6h:"पहला कदम",c6p:"यदि आप नए हैं: धीरे शुरू करें। एक फिल्म। एक संकेत। छोटा कदम—पर सचेत।",c6a:"फिल्में व अध्याय →"}, footer:{lead:"© Lampadēphóros • संपर्क:"}},
  bn:{ pageTitle:"Lampadēphóros – আমাদের সম্পর্কে", brandMini:"মশালবাহক", h1:"আমাদের সম্পর্কে", sub:"Lampadēphóros অর্থ “মশালবাহক”: না শোরগোল, না প্রদর্শন—শুধু এমন আলো যা পথ দেখায়। আলো, জল, হৃদয় ও নীরবতার পথ।", note:"স্প্যাম নয়। ড্রামা নয়। শুধু কাজ।", nav:{start:"Start",about:"আমাদের সম্পর্কে",films:"ফিল্ম ও অধ্যায়",impulses:"ইমপালস",workshop:"ওয়ার্কশপ",offers:"অফার",shop:"শপ",links:"আমাদের খুঁজুন"}, cards:{c1h:"Lampadēphóros কে?",c1p1:"আধ্যাত্মিক গভীরতা সহ একটি সৃজনশীল মিডিয়া প্রকল্প। আমরা গল্প বলি, ছবি গড়ি, চিন্তা গুছাই—এবং যা সত্যিই ধরে রাখে তা খুঁজি।",c1p2:"সংক্ষেপে: যারা আলো চায়—শোর ছাড়াই—তাদের জন্য একটি জায়গা।",c2h:"আমরা কেন আছি?",c2p:"কারণ অনেকেই অর্থ খোঁজে আর শুধু শোর পায়। আমরা বিশ্বাস করি: নীরবতা খালি নয়; সেখানে সত্য আবার শোনা যায়।",c3h:"আমাদের লক্ষ্য",c3p:"শোর ছাড়াই দৃশ্যমানতা। ভয় ছাড়াই গভীরতা। এমন কনটেন্ট যা ভিত্তি দেয়, তোলে, আর হৃদয় জাগায়—ধাপে ধাপে।",c4h:"আমরা কীসের পক্ষে",c4p1:"ক্লিকবেইট নয়—স্বচ্ছতা। ড্রামা নয়—মর্যাদা। বিদ্রূপ নয়—সৌন্দর্য। ট্রেন্ড নয়—বিশ্বস্ততা।",c4p2:"আমরা ধীরে গড়ি—কিন্তু সত্যি।",c5h:"এখানে কী পাবেন",c5p:"ফিল্ম ও অধ্যায়, ইমপালস, ওয়ার্কশপ নোট, অফার (তীর্থযাত্রা, ওয়ার্কশপ, বক্তৃতা)—পরে শপ।",c5a:"ওভারভিউ →",c6h:"প্রথম পদক্ষেপ",c6p:"নতুন হলে: ধীরে শুরু করুন। একটিই ফিল্ম। একটিই ইমপালস। ছোট পদক্ষেপ—কিন্তু সচেতন।",c6a:"ফিল্ম ও অধ্যায় →"}, footer:{lead:"© Lampadēphóros • যোগাযোগ:"}},
  id:{ pageTitle:"Lampadēphóros – Tentang", brandMini:"Pembawa Obor", h1:"Tentang", sub:"Lampadēphóros berarti “pembawa obor”: bukan bising, bukan pamer—melainkan terang yang memberi arah. Jalan dari terang, air, hati, dan hening.", note:"Tanpa spam. Tanpa drama. Hanya karya.", nav:{start:"Start",about:"Tentang",films:"Film & bab",impulses:"Impuls",workshop:"Bengkel",offers:"Penawaran",shop:"Toko",links:"Temukan kami"}, cards:{c1h:"Siapa Lampadēphóros?",c1p1:"Proyek media kreatif dengan kedalaman rohani. Kami bercerita, membangun gambar, menata pikiran—dan mencari yang benar-benar menopang.",c1p2:"Singkatnya: tempat bagi yang ingin terang—tanpa bising.",c2h:"Mengapa kami ada?",c2p:"Karena banyak orang mencari makna dan hanya menemukan kebisingan. Kami percaya: hening bukan kosong; itu ruang agar kebenaran terdengar lagi.",c3h:"Tujuan kami",c3p:"Terlihat tanpa bising. Dalam tanpa takut. Konten yang membumi, mengangkat, dan membangunkan hati—selangkah demi selangkah.",c4h:"Apa yang kami junjung",c4p1:"Kejelasan bukan clickbait. Martabat bukan drama. Keindahan bukan sinisme. Kesetiaan bukan tren.",c4p2:"Kami membangun pelan—tapi nyata.",c5h:"Yang kamu temukan di sini",c5p:"Film & bab, impuls, bengkel, penawaran (ziarah, workshop, talk)—dan nanti toko.",c5a:"Ringkasan →",c6h:"Ambil langkah pertama",c6p:"Kalau kamu baru: mulai pelan. Satu film. Satu impuls. Langkah kecil—tapi sadar.",c6a:"Ke Film & bab →"}, footer:{lead:"© Lampadēphóros • Kontak:"}},
  fil:{ pageTitle:"Lampadēphóros – Tungkol", brandMini:"Tagapagdala ng Sulo", h1:"Tungkol", sub:"Ang Lampadēphóros ay “tagapagdala ng sulo”: hindi maingay, hindi pakitang-tao—kundi liwanag na gumagabay. Landas ng liwanag, tubig, puso at katahimikan.", note:"Walang spam. Walang drama. Gawa lang.", nav:{start:"Start",about:"Tungkol",films:"Mga Pelikula at Kabanata",impulses:"Mga Impulse",workshop:"Workshop",offers:"Mga Alok",shop:"Shop",links:"Saan kami makikita"}, cards:{c1h:"Sino ang Lampadēphóros?",c1p1:"Isang malikhaing media project na may espiritwal na lalim. Nagkukuwento kami, bumubuo ng mga larawan, inaayos ang mga isip—at hinahanap ang tunay na sumusuporta.",c1p2:"Sa madaling sabi: lugar para sa gustong liwanag—walang ingay.",c2h:"Bakit kami umiiral?",c2p:"Dahil marami ang naghahanap ng kahulugan at ingay lang ang nakikita. Naniniwala kami: hindi walang laman ang katahimikan; dito muling naririnig ang katotohanan.",c3h:"Layunin namin",c3p:"Pagiging nakikita nang walang ingay. Lalim na walang takot. Nilalamang nagpapalapat sa lupa, umaangat, at gumigising sa puso—hakbang-hakbang.",c4h:"Pinaninindigan namin",c4p1:"Linaw kaysa clickbait. Dangal kaysa drama. Ganda kaysa sinismo. Katapatan kaysa uso.",c4p2:"Dahan-dahan kaming bumubuo—pero totoo.",c5h:"Makikita mo dito",c5p:"Mga pelikula at kabanata, impulses, workshop notes, mga alok (pilgrimage, workshops, talks)—at kalaunan shop.",c5a:"Overview →",c6h:"Unang hakbang",c6p:"Kung bago ka: magsimula nang dahan-dahan. Isang pelikula. Isang impulse. Maliit na hakbang—pero may kamalayan.",c6a:"Sa Mga Pelikula at Kabanata →"}, footer:{lead:"© Lampadēphóros • Kontak:"}},
  ja:{ pageTitle:"Lampadēphóros – 私たちについて", brandMini:"たいまつを運ぶ者", h1:"私たちについて", sub:"Lampadēphóros は「たいまつを運ぶ者」。騒がしくなく、派手でもない—道を照らす光。光・水・心・静けさの道。", note:"スパムなし。ドラマなし。作品だけ。", nav:{start:"Start",about:"私たちについて",films:"映画と章",impulses:"インパルス",workshop:"工房",offers:"案内",shop:"ショップ",links:"見つける"}, cards:{c1h:"Lampadēphórosとは？",c1p1:"霊的な深みをもつクリエイティブなメディアプロジェクト。物語を語り、映像を作り、思考を整え—本当に支えるものを探します。",c1p2:"要するに：騒がずに光を求める人の場所。",c2h:"なぜ存在する？",c2p:"多くの人が意味を求めても騒音ばかり。私たちは信じます：沈黙は空ではなく、真実が再び聞こえる空間です。",c3h:"目的",c3p:"騒がずに可視化。恐れのない深み。心を地に足つけ、持ち上げ、目覚めさせる内容を—一歩ずつ。",c4h:"大切にすること",c4p1:"クリックベイトより明晰さ。ドラマより尊厳。皮肉より美。流行より忠実さ。",c4p2:"ゆっくり—でも本物に。",c5h:"ここにあるもの",c5p:"映画と章、短いインパルス、工房、案内（巡礼、ワークショップ、講話）—そして後にショップ。",c5a:"概要 →",c6h:"最初の一歩",c6p:"初めてなら：静かに始めよう。一本の映画。ひとつの言葉。小さな一歩—でも意識的に。",c6a:"映画と章へ →"}, footer:{lead:"© Lampadēphóros • 連絡:"}},
  ko:{ pageTitle:"Lampadēphóros – 소개", brandMini:"횃불을 드는 이", h1:"소개", sub:"Lampadēphóros는 “횃불을 드는 이”라는 뜻입니다. 시끄럽지 않고 과장되지 않으며—길을 비추는 빛입니다. 빛, 물, 마음, 침묵의 길.", note:"스팸 없음. 드라마 없음. 작업만.", nav:{start:"Start",about:"소개",films:"영상 & 장",impulses:"임펄스",workshop:"작업실",offers:"제안",shop:"샵",links:"찾아오기"}, cards:{c1h:"Lampadēphóros는 누구?",c1p1:"영적 깊이를 지닌 창작 미디어 프로젝트입니다. 이야기를 전하고, 이미지를 만들고, 생각을 정리하며—진짜 버팀목을 찾습니다.",c1p2:"한마디로: 소음 없이 빛을 원하는 사람들의 장소.",c2h:"왜 존재하나?",c2p:"많은 이들이 의미를 찾지만 소음만 만납니다. 우리는 믿습니다: 침묵은 비어 있지 않고, 진리가 다시 들리는 공간입니다.",c3h:"목표",c3p:"소음 없는 가시성. 두려움 없는 깊이. 마음을 붙들고 일으키는 콘텐츠—한 걸음씩.",c4h:"우리가 지키는 것",c4p1:"클릭베이트보다 명료함. 드라마보다 존엄. 냉소보다 아름다움. 유행보다 충실함.",c4p2:"천천히—하지만 진짜로.",c5h:"여기에서 찾는 것",c5p:"영상 & 장, 임펄스, 작업실, 제안(순례, 워크숍, 강연)—그리고 추후 샵.",c5a:"개요 →",c6h:"첫 걸음",c6p:"처음이라면: 천천히 시작하세요. 영상 하나. 임펄스 하나. 작은 걸음—하지만 의식적으로.",c6a:"영상 & 장으로 →"}, footer:{lead:"© Lampadēphóros • 연락:"}},
  vi:{ pageTitle:"Lampadēphóros – Giới thiệu", brandMini:"Người mang đuốc", h1:"Giới thiệu", sub:"Lampadēphóros nghĩa là “người mang đuốc”: không ồn ào, không phô trương—mà là ánh sáng dẫn đường. Con đường của ánh sáng, nước, trái tim và sự tĩnh lặng.", note:"Không spam. Không drama. Chỉ công việc.", nav:{start:"Start",about:"Giới thiệu",films:"Phim & chương",impulses:"Gợi ý",workshop:"Xưởng",offers:"Đề nghị",shop:"Cửa hàng",links:"Tìm chúng tôi"}, cards:{c1h:"Lampadēphóros là ai?",c1p1:"Một dự án truyền thông sáng tạo với chiều sâu thiêng liêng. Chúng tôi kể chuyện, xây hình ảnh, sắp xếp suy nghĩ—và tìm điều thật sự nâng đỡ.",c1p2:"Tóm lại: nơi dành cho người muốn ánh sáng—không ồn.",c2h:"Vì sao tồn tại?",c2p:"Vì nhiều người tìm ý nghĩa nhưng chỉ gặp tiếng ồn. Chúng tôi tin: sự tĩnh lặng không rỗng; đó là không gian để chân lý được nghe lại.",c3h:"Mục tiêu",c3p:"Hiện diện không ồn. Sâu mà không sợ. Nội dung giúp bám đất, nâng lên và đánh thức trái tim—từng bước.",c4h:"Chúng tôi đứng về điều gì",c4p1:"Rõ ràng hơn clickbait. Phẩm giá hơn drama. Đẹp hơn cay độc. Trung tín hơn xu hướng.",c4p2:"Xây chậm—nhưng thật.",c5h:"Bạn sẽ thấy gì",c5p:"Phim & chương, gợi ý, xưởng, đề nghị (hành hương, workshop, bài nói)—và sau này cửa hàng.",c5a:"Tổng quan →",c6h:"Bước đầu tiên",c6p:"Nếu bạn mới: bắt đầu nhẹ nhàng. Một phim. Một gợi ý. Bước nhỏ—nhưng có ý thức.",c6a:"Đến Phim & chương →"}, footer:{lead:"© Lampadēphóros • Liên hệ:"}},
  ms:{ pageTitle:"Lampadēphóros – Tentang", brandMini:"Pembawa Obor", h1:"Tentang", sub:"Lampadēphóros bermaksud “pembawa obor”: bukan bising, bukan berlagak—tetapi cahaya yang memberi arah. Jalan cahaya, air, hati dan sunyi.", note:"Tiada spam. Tiada drama. Hanya karya.", nav:{start:"Start",about:"Tentang",films:"Filem & bab",impulses:"Impuls",workshop:"Bengkel",offers:"Tawaran",shop:"Kedai",links:"Cari kami"}, cards:{c1h:"Siapa Lampadēphóros?",c1p1:"Projek media kreatif dengan kedalaman rohani. Kami bercerita, membina imej, menyusun fikiran—dan mencari yang benar-benar menyokong.",c1p2:"Ringkasnya: tempat untuk yang mahukan cahaya—tanpa bising.",c2h:"Mengapa kami wujud?",c2p:"Kerana ramai mencari makna dan hanya menemui kebisingan. Kami percaya: sunyi tidak kosong; ia ruang untuk kebenaran didengar kembali.",c3h:"Matlamat kami",c3p:"Keterlihatan tanpa bising. Kedalaman tanpa takut. Kandungan yang membumi, mengangkat dan membangunkan hati—langkah demi langkah.",c4h:"Apa yang kami pegang",c4p1:"Kejelasan bukan clickbait. Maruah bukan drama. Keindahan bukan sinis. Kesetiaan bukan trend.",c4p2:"Kami membina perlahan—tetapi nyata.",c5h:"Apa yang ada di sini",c5p:"Filem & bab, impuls, bengkel, tawaran (ziarah, bengkel, ceramah)—dan nanti kedai.",c5a:"Gambaran →",c6h:"Ambil langkah pertama",c6p:"Jika anda baru: mula perlahan. Satu filem. Satu impuls. Langkah kecil—tetapi sedar.",c6a:"Ke Filem & bab →"}, footer:{lead:"© Lampadēphóros • Hubungi:"}},
  ta:{ pageTitle:"Lampadēphóros – எங்களை பற்றி", brandMini:"தீப்பந்தம் தாங்கி", h1:"எங்களை பற்றி", sub:"Lampadēphóros என்பதின் பொருள் “தீப்பந்தம் தாங்குபவர்”: சத்தமில்லை, காட்சிச்சமையலும் இல்லை—பாதை காட்டும் ஒளி. ஒளி, நீர், இதயம், அமைதி ஆகியவற்றின் பாதை.", note:"ஸ்பாம் இல்லை. நாடகம் இல்லை. வேலை மட்டும்.", nav:{start:"Start",about:"எங்களை பற்றி",films:"திரைப்படங்கள் & அத்தியாயங்கள்",impulses:"தூண்டுதல்கள்",workshop:"பணிமனை",offers:"சலுகைகள்",shop:"கடை",links:"எங்களை காண"} , cards:{c1h:"Lampadēphóros யார்?",c1p1:"ஆன்மீக ஆழமுள்ள ஒரு படைப்பூக்க ஊடகத் திட்டம். கதைகள் சொல்கிறோம், படங்களை உருவாக்குகிறோம், எண்ணங்களை ஒழுங்குபடுத்துகிறோம்—உண்மையில் தாங்குவதைத் தேடுகிறோம்.",c1p2:"சுருக்கமாக: சத்தமின்றி ஒளியை விரும்புவோருக்கான இடம்.",c2h:"ஏன் இருக்கிறோம்?",c2p:"பலர் அர்த்தம் தேடுகிறார்கள்; ஆனால் சத்தமே கிடைக்கிறது. அமைதி காலியானது அல்ல; அதில் உண்மை மீண்டும் கேட்கப்படும்.",c3h:"எங்கள் இலக்கு",c3p:"சத்தமின்றி வெளிப்பாடு. பயமின்றி ஆழம். நிலைபெறச் செய்து, உயர்த்தி, இதயத்தை விழிப்பாக்கும் உள்ளடக்கம்—படி படியாக.",c4h:"எங்கள் நிலைப்பாடு",c4p1:"கிளிக்பேட் அல்ல—தெளிவு. நாடகம் அல்ல—மரியாதை. சினிசம் அல்ல—அழகு. போக்கு அல்ல—நேர்மை.",c4p2:"மெதுவாக கட்டுகிறோம்—ஆனால் உண்மை.",c5h:"இங்கே கிடைப்பது",c5p:"திரைப்படங்கள் & அத்தியாயங்கள், தூண்டுதல்கள், பணிமனை, சலுகைகள் (யாத்திரை, பணிமனை, உரைகள்)—பின்னர் கடை.",c5a:"மேலோட்டம் →",c6h:"முதல் படி",c6p:"நீங்கள் புதியவர் என்றால்: மெதுவாக தொடங்குங்கள். ஒரு படம். ஒரு தூண்டுதல். சிறிய படி—ஆனால் விழிப்புடன்.",c6a:"திரைப்படங்கள் & அத்தியாயங்கள் →"}, footer:{lead:"© Lampadēphóros • தொடர்பு:"}},
  ku:{ pageTitle:"Lampadēphóros – Derbarê me de", brandMini:"Hilgirê Meşalê", h1:"Derbarê me de", sub:"Lampadēphóros wateya “hilgirê meşalê” ye: ne qereqol, ne pêşandana—belkî ronahiyek ku rê nîşan dide. Rêya ronahî, av, dil û bêdengî.", note:"Spem tune. Drama tune. Tenê kar.", nav:{start:"Start",about:"Derbarê me de",films:"Fîlm û beş",impulses:"Têkdan",workshop:"Atolye",offers:"Pêşkêş",shop:"Firoşgeh",links:"Li ku em in"}, cards:{c1h:"Lampadēphóros kî ye?",c1p1:"Projeyek medyayê ya afirîner bi qelewîya ruhî. Em çîrok dibêjin, wêne ava dikin, fikiran rêk dixin—û tiştê ku rastî hilgire digerin.",c1p2:"Kurte: cihê ji bo kesên ku ronahî dixwazin—bê deng.",c2h:"Çima em hene?",c2p:"Ji ber ku gelek kes manayê digerin û pir caran tenê deng dibînin. Em bawer dikin: bêdengî vala nîne; ew cih e ku rastî dîsa tê bihîstin.",c3h:"Armanca me",c3p:"Dîtin bê deng. Qelewî bê tirs. Naverok ku bingeh dide, bilind dike û dil şiyar dike—gav bi gav.",c4h:"Em li ser çi radiestîn?",c4p1:"Rastbînî li şûna clickbait. Rûmet li şûna drama. Bedewî li şûna cynîzm. Wefadarî li şûna trend.",c4p2:"Em hêdî ava dikin—lê rast.",c5h:"Tu li vir çi dibînî?",c5p:"Fîlm û beş, têkdan, atolye, pêşkêş (zîret, atolye, axaftin)—û paşê firoşgeh.",c5a:"Têgihiştin →",c6h:"Gava yekem",c6p:"Heke tu nû yî: bi aramî dest pê bike. Fîlmek. Têkdanek. Gavek piçûk—lê bi şuur.",c6a:"Biçe ser Fîlm û beş →"}, footer:{lead:"© Lampadēphóros • Têkilî:"}}
};
